# serverless.yml
# Primary Source: https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
# Events Source: https://serverless.com/framework/docs/providers/aws/events/apigateway/

service: solium-project

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  memorySize: 512
  timeout: 50
  profile: blankservice # aws configure --profile blankservice

package:
  exclude:
    - node_modules/**
  include:
    - node_modules/moment/**

functions:
  calc:
    handler: lib/endpoints.calc
    description: Runs a calculation on vesting data
    events:
      - http:
          path: calc
          method: post
